auth_enabled: false

server:
  http_listen_port: 3100
  # increase allowed message size if you run into "grpc: received message larger than max"
  grpc_server_max_recv_msg_size: 33554432  # 32MB
  grpc_server_max_send_msg_size: 33554432  # 32MB

limits_config:
  # Increase the Ingestion Rate Limit so Loki would be able to handle larger logs amount
  # The rate is calculated per second!
  # Defaults: 4 and 6
  ingestion_rate_mb: 40
  ingestion_burst_size_mb: 80
  # Increase stream rate limit. Single stream is data matchin specific labels, eg "service_name"
  # Defaults: 3MB and 15MB
  per_stream_rate_limit: 50MB
  per_stream_rate_limit_burst: 100MB
  # Increase limit for single log line size
  # Defaults: 256KB
  max_line_size: 52428800 # 50MB
  # Data retention setting. This depends on compactor settings!
  retention_period: 48h

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

compactor:
  working_directory: /loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h